name: another_notes
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
